server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:C:/Users/maslke/Documents/GitHub/spring-cloud-in-action/chapter3/confsvr/src/main/resources/config/licensingservice