server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: env,health,info,refresh

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:7061/eureka
