management:
  endpoints:
    web:
      exposure:
        include: env,health,info,refresh

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8901/auth/user

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:7061/eureka

logging:
  level:
    com.netflix: debug
    org.springframework.web: debug
    com.maslke.spring: debug