management:
  endpoints:
    web:
      exposure:
        include: env,health,info,refresh


server:
  port: 8081

spring:
  application:
    name: licensingservice
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888
