management:
  endpoints:
    web:
      exposure:
        include: env,health,info,refresh


server:
  port: 8081

spring:
  application:
    name: licensingservice
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        inOrgChange:
          destination: stream-topic

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

security:
  oauth2:
    client:
      client-id: eagleeye # security.oauth2.client.client-id 属性是在配置OAuth2RestTemplate bean的时候，需要的。
    resource:
      user-info-uri: http://localhost:8901/auth/user
